{% set name = "pydata-google-auth" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydata-google-auth-{{ version }}.tar.gz
  sha256: 547b6c0fbea657dcecd50887c5db8640ebec062a59a2b88e8ff8e53a04818303

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - setuptools
    - google-auth >=1.25.0,<3.0
    - google-auth-oauthlib >=0.4.0

test:
  imports:
    - pydata_google_auth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pydata/pydata-google-auth
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Helpers for authenticating to Google APIs from Python.

  description: |
    pydata-google-auth adds helpers to authenticate with end-user credentials
    to Google APIs from Python. It wraps the official google-auth and
    google-auth-oauthlib libraries.
  doc_url: http://pydata-google-auth.readthedocs.io/
  dev_url: https://github.com/pydata/pydata-google-auth

extra:
  recipe-maintainers:
    - leahecole
    - chalmerlowe
    - tswast
