{% set name = "pydata-google-auth" %}
{% set version = "1.3.0" %}
{% set sha256 = "eb8dfcbc787507e5a538f18194295511b4b580370365cc1592d6d22bd6c2bc27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - google-auth >=1.25.0,<3.0dev
    - google-auth-oauthlib >=0.4.0
    - setuptools

test:
  imports:
    - pydata_google_auth

about:
  home: https://github.com/pydata/pydata-google-auth
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Helpers for authenticating to Google APIs from Python.

  description: |
    pydata-google-auth adds helpers to authenticate with end-user credentials
    to Google APIs from Python. It wraps the official google-auth and
    google-auth-oauthlib libraries.
  doc_url: http://pydata-google-auth.readthedocs.io/
  dev_url: https://github.com/pydata/pydata-google-auth

extra:
  recipe-maintainers:
    - leahecole
    - tswast
